import '@testing-library/jest-dom/vitest';
import React from 'react';

import { render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';

vi.mock('@vercel/analytics/next', () => ({
	__esModule: true,
	Analytics: () => <div data-testid="analytics" />, 
}));

vi.mock('next/font/google', () => ({
	__esModule: true,
	Geist: () => ({ variable: '--font-geist-sans' }),
	Geist_Mono: () => ({ variable: '--font-geist-mono' }),
}));

vi.mock('./globals.css', () => ({}));

import RootLayout, { metadata } from './layout';

describe('RootLayout', () => {
	it('provides metadata', () => {
		expect(metadata).toMatchObject({
			title: 'Next App',
			description: 'Generated by create next app',
		});
	});

	it('renders children and analytics with combined font classes', () => {
		render(<RootLayout><div>content</div></RootLayout>);

		const body = document.querySelector('body');
		expect(body).toHaveClass('--font-geist-sans', '--font-geist-mono', 'antialiased');
		expect(screen.getByText('content')).toBeInTheDocument();
		expect(screen.getByTestId('analytics')).toBeInTheDocument();
	});
});
